### ISSUE TITLE
可以正常使用，辛苦了

### ISSUE THREAD

**Issue by asdqian** [SpaceEggs/B450M-Mortar-Max-Hackintosh#1]
对了问下，BIG SUR小版本升级应该可以直接升级吧

**Comment by SpaceEggs** [comment]
目前升级都正常

**Comment by asdqian** [comment]
嗯嗯  我是B450M 火箭筒，不过用着也正常。除了机箱前面的USB3.0口不能用。还有就是8111 3.0版本驱动好像有问题，不能连接网络，要手动修改网络硬件配置。

**Comment by jimlgx** [comment]
感谢 @SpaceEggs ，主板 cpu 显卡完全一样，系统升级BIG SUR主要功能正常，小问题是每次输入用户名密码登陆成功后，键盘失灵，需要重新插拔一次键盘U口

**Comment by SpaceEggs** [comment]
> 感谢 @SpaceEggs ，主板 cpu 显卡完全一样，系统升级BIG SUR主要功能正常，小问题是每次输入用户名密码登陆成功后，键盘失灵，需要重新插拔一次键盘U口

我这边没有出现该问题。 filco 键盘 

检查一下键盘是不是接的 usb2.0 接口，或者更换 usb 接口试试。
