### ISSUE TITLE
换了新的efi进不去系统

### ISSUE THREAD

**Issue by asdqian** [SpaceEggs/B450M-Mortar-Max-Hackintosh#3]
昨天我下载后修改了机型三码这些信息。然后把老的efi文件删掉。把新的复制进去。开机提示 oc :failed to load configutation。  oc引导界面都没进去。 我没找到原因，又用回你之前的0.6.3版本了。

**Comment by asdqian** [comment]
爬到了一个帖子。等会儿试试。http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1878272&highlight=%CA%A7%B0%DC

**Comment by SpaceEggs** [comment]
把U盘格式化成HFS格式，把EFI放进U盘中，用U盘引导试试。

进去的时候重置一下 NVRAM

**Comment by asdqian** [comment]
好的 多谢。

**Comment by asdqian** [comment]
确实可以了。我把EFI文件放进以前装big sur刻录的U盘OC分区。用U盘OC启动，重置了下NVRAM，拔掉U盘再开机就能正常引导了。不过这时不能在从硬盘上的OC引导的情况下重置NVRAM。要不然还会进不去OC。

**Comment by SpaceEggs** [comment]
已更新 OC 0.6.5。

建议更新后重新尝试下。

如果近期有更新过 Bios，请将 Booter -> Quirks -> SetupVirtualMap 设为 No

**Comment by asdqian** [comment]
好的 多谢

**Comment by asdqian** [comment]
新年快乐啊 老哥
