### ISSUE TITLE
有个问题，CPU型号显示未知

### ISSUE THREAD

**Issue by asdqian** [SpaceEggs/B450M-Mortar-Max-Hackintosh#5]
老哥我CPU是R5 2600 。之前用的0.6.5 ， processortype数值为0的话的能识别成i5六核，这次用了0.6.7，processortype值还是保持0，但是关于本机那里cpu型号无法识别了。显示未知。

**Comment by SpaceEggs** [comment]
https://oc.skk.moe/10-platform-info.html#27-ProcessorType

**Comment by asdqian** [comment]
> https://oc.skk.moe/10-platform-info.html#27-ProcessorType
好的老哥 我看看，多谢

**Comment by asdqian** [comment]
解决了。https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/IndustryStandard/AppleSmBios.h
这里可以查cpu对应得十六进制数值。我选择的是六核心的i5,十六进制是0601，转换成10进制是1537，就把processortype里原来的0改为1537，重启就能识别了

**Comment by asdqian** [comment]
哦 看错了 。你发给我的链接里就有这个链接了。没看到 😵
